version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - ./api-gateway/.env
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    env_file:
      - ./admin/.env
    networks:
      - app-network

  jwt-go:
    build:
      context: ./jwt-go
      dockerfile: Dockerfile
    env_file:
      - ./jwt-go/.env
    networks:
      - app-network

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file:
      - ./user/.env
    networks:
      - app-network

  leader:
    build:
      context: ./leader
      dockerfile: Dockerfile
    environment:
      ENV_TYPE: prod
    volumes:
      - ./leader/config:/app/config
    networks:
      - app-network

  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    environment:
      ENV_TYPE: prod
    volumes:
      - ./manager/config:/app/config
    networks:
      - app-network

  notification:
      build:
        context: ./notification
        dockerfile: Dockerfile
      volumes:
        - ./notification/config:/app/config
      networks:
        - app-network


networks:
  app-network:
    driver: bridge
