// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/role-leader.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoleLeader_CreateFeedback_FullMethodName   = "/RoleLeader/CreateFeedback"
	RoleLeader_GetMeeting_FullMethodName       = "/RoleLeader/GetMeeting"
	RoleLeader_GetLeaderMeeting_FullMethodName = "/RoleLeader/GetLeaderMeeting"
)

// RoleLeaderClient is the client API for RoleLeader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleLeaderClient interface {
	CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*CreateFeedbackResponse, error)
	GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*GetMeetingResponse, error)
	GetLeaderMeeting(ctx context.Context, in *GetLeaderMeetingsRequest, opts ...grpc.CallOption) (*GetLeaderMeetingsResponse, error)
}

type roleLeaderClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleLeaderClient(cc grpc.ClientConnInterface) RoleLeaderClient {
	return &roleLeaderClient{cc}
}

func (c *roleLeaderClient) CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*CreateFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFeedbackResponse)
	err := c.cc.Invoke(ctx, RoleLeader_CreateFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleLeaderClient) GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*GetMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeetingResponse)
	err := c.cc.Invoke(ctx, RoleLeader_GetMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleLeaderClient) GetLeaderMeeting(ctx context.Context, in *GetLeaderMeetingsRequest, opts ...grpc.CallOption) (*GetLeaderMeetingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderMeetingsResponse)
	err := c.cc.Invoke(ctx, RoleLeader_GetLeaderMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleLeaderServer is the server API for RoleLeader service.
// All implementations must embed UnimplementedRoleLeaderServer
// for forward compatibility.
type RoleLeaderServer interface {
	CreateFeedback(context.Context, *CreateFeedbackRequest) (*CreateFeedbackResponse, error)
	GetMeeting(context.Context, *GetMeetingRequest) (*GetMeetingResponse, error)
	GetLeaderMeeting(context.Context, *GetLeaderMeetingsRequest) (*GetLeaderMeetingsResponse, error)
	mustEmbedUnimplementedRoleLeaderServer()
}

// UnimplementedRoleLeaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleLeaderServer struct{}

func (UnimplementedRoleLeaderServer) CreateFeedback(context.Context, *CreateFeedbackRequest) (*CreateFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeedback not implemented")
}
func (UnimplementedRoleLeaderServer) GetMeeting(context.Context, *GetMeetingRequest) (*GetMeetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeeting not implemented")
}
func (UnimplementedRoleLeaderServer) GetLeaderMeeting(context.Context, *GetLeaderMeetingsRequest) (*GetLeaderMeetingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderMeeting not implemented")
}
func (UnimplementedRoleLeaderServer) mustEmbedUnimplementedRoleLeaderServer() {}
func (UnimplementedRoleLeaderServer) testEmbeddedByValue()                    {}

// UnsafeRoleLeaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleLeaderServer will
// result in compilation errors.
type UnsafeRoleLeaderServer interface {
	mustEmbedUnimplementedRoleLeaderServer()
}

func RegisterRoleLeaderServer(s grpc.ServiceRegistrar, srv RoleLeaderServer) {
	// If the following call pancis, it indicates UnimplementedRoleLeaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleLeader_ServiceDesc, srv)
}

func _RoleLeader_CreateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleLeaderServer).CreateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleLeader_CreateFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleLeaderServer).CreateFeedback(ctx, req.(*CreateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleLeader_GetMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleLeaderServer).GetMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleLeader_GetMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleLeaderServer).GetMeeting(ctx, req.(*GetMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleLeader_GetLeaderMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderMeetingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleLeaderServer).GetLeaderMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleLeader_GetLeaderMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleLeaderServer).GetLeaderMeeting(ctx, req.(*GetLeaderMeetingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleLeader_ServiceDesc is the grpc.ServiceDesc for RoleLeader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleLeader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RoleLeader",
	HandlerType: (*RoleLeaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFeedback",
			Handler:    _RoleLeader_CreateFeedback_Handler,
		},
		{
			MethodName: "GetMeeting",
			Handler:    _RoleLeader_GetMeeting_Handler,
		},
		{
			MethodName: "GetLeaderMeeting",
			Handler:    _RoleLeader_GetLeaderMeeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/role-leader.proto",
}
